title: Blog de Engenharia de Dados — Helder Jr.
description: Publicações técnicas baseadas em experiências reais com dados, automações e SQL.

remote_theme: pages-themes/minimal@v0.3.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

markdown: kramdown
permalink: pretty